enum
{
    KeysMode_None = 0,
    KeysMode_Underscores,
    KeysMode_NoBlanks,
    KeysMode_COUNT
};

enum
{
    SpeedMode_None = 0,
    SpeedMode_Float,
    SpeedMode_Integer,
    SpeedMode_COUNT
};

enum
{
    Round_Down = 0,
    Round_Nearest = 1,
    Round_Up = 2,
    Round_COUNT
};

enum
{
    Takeoff_None = 0,
    Takeoff_Jump,
    Takeoff_All,
    Takeoff_COUNT
};

enum
{
    SpeedColor_None = 0,
    SpeedColor_Speed,
    SpeedColor_GainInstant,
    SpeedColor_GainAverage,
    SpeedColor_COUNT
}